#!/usr/bin/php
<?php
if ( !isset( $argv[1] ) ) {
	$script_name = basename( __FILE__ );
	echo "Usage: $script_name <config_file>.php\n";
	exit;
}

$config_file_path = dirname( __FILE__ ) . '/' . $argv[1];

if ( !file_exists( $config_file_path ) ) {
	echo "Could not find config file $config_file_path.\n";
	exit;
}

include $config_file_path;

if ( !file_exists( $log_path ) ) {
	echo "Could not find log path $log_path.\n";
	exit;
}

if ( !isset( $argv[2] ) ) {
	system( "tail -f $log_path | {$argv[0]} {$argv[1]} watch" );
	exit;
}

function passes_filter( $block, $regexes ) {
	foreach ( $regexes as $regex ) {
		if ( preg_match( $regex, $block ) ) {
			return false;
		}
	}

	return true;
}

function is_trace_start( $line ) {
	return preg_match( '@^\[(.*?)\] PHP Stack trace:@', $line );
}

function is_trace_line( $line ) {
	return preg_match( '@^\[(.*?)\] PHP \s+[0-9]+\.@', $line );
}

$is_tracing = false;
$block = '';
$fp = fopen( 'php://stdin', 'r' );
while ( ( $line = fgets( $fp ) ) !== false ) {

	if ( !is_trace_start( $line ) && !is_trace_line( $line ) ) {

		if ( passes_filter( $block, $regexes ) ) {
			echo $block;
		}
		
		$is_tracing = false;
		$block = $line;
		continue;
	}

	if ( $block && is_trace_start( $line ) ) {
		$is_tracing = true;
		$block .= $line;
		continue;
	}

	if ( $is_tracing && is_trace_line( $line ) ) {
		$block .= $line;
	}

}
